### ISSUE TITLE
請問RAS-50NJF / RAC-50NK1機型沒有室外溫度的屬性

### ISSUE THREAD

**Issue by dragonyeh** [qqaatw/JciHitachiHA#1]
感謝您開發這個整合HA插件，實在太好用了!!
另請問室外機的溫度在HA找不到此實體或屬性，有可能是哪裡的問題(HA版本2021.8.8)

**Comment by qqaatw** [comment]
Hello,

請問你使用的版本是最新的`0.0.4`嗎？ 我這邊測試HA v2021.9.2 可以正常顯示室外溫度。

**Comment by dragonyeh** [comment]
是的，我安裝的是最新0.0.4版。
![image](https://user-images.githubusercontent.com/64698316/132084804-a242ccb2-dd0c-47d0-b769-87a16ff149ec.png)

**Comment by qqaatw** [comment]
室外溫度是一個獨立的sensor entity，不會出現在climate entity的屬性 (climate entity沒有支援室外溫度)。 您再確認看看。

若還是沒有看到的話，麻煩你幫我在`configuration.yaml`內加上如下的Debug設定，並在重啟HA後查看log確認是否有一項outdoor_temp的欄位以及欄位數值。 照理來說，尊榮型應該都有支援室外溫度。
```
logger:
  default: info
  logs:
    custom_components.jcihitachi_tw: debug
```
