### ISSUE TITLE
360HH1 無法控制air speed

### ISSUE THREAD

**Issue by mustang-hsu** [qqaatw/JciHitachiHA#62]
### 🐛 Describe the bug

360HH1 控制裏面沒有air speed這個選項，是否還沒有支援
![IMG_1117](https://github.com/qqaatw/JciHitachiHA/assets/83499874/33f67357-a3a7-47f6-bbda-e9abf2b73d4e)
![IMG_1118](https://github.com/qqaatw/JciHitachiHA/assets/83499874/bfe72aa1-04de-4986-82d7-ca2695b5b48f)

240HH有這個選項

### Environment Information

![IMG_1126](https://github.com/qqaatw/JciHitachiHA/assets/83499874/4c3c89ef-1d18-4a44-86f8-99b7d8accc7b)

JciHitachiHA version最新

除濕機 Rd-360HH1

**Comment by qqaatw** [comment]
Please enable debug logging and then attach your full log here, thanks.

```yaml
logger:
  default: info
  logs:
    custom_components.jcihitachi_tw: debug
```
