### ISSUE TITLE
Automation stopped execution on 2024.05

### ISSUE THREAD

**Issue by J1A-T13N** [qqaatw/JciHitachiHA#78]
## 🐛 Describe the bug

透過服務呼叫 climate.turn_off 或自動化設定HVAC模式時會發生錯誤。

> [!CAUTION]
> 錯誤：Detected that custom integration 'jcihitachi_tw' calls async_write_ha_state from a thread at custom_components/jcihitachi_tw/__init__.py, line 246: self.coordinator.async_set_updated_data(None). Please report it to the author of the 'jcihitachi_tw' custom integration.

>Automation script: 
```
alias: 智慧-房間冷氣開關
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - climate.bedroom_room
    for:
      hours: 1
      minutes: 0
      seconds: 0
    attribute: temperature
    above: sensor.weather_feels_like_temperature
    id: off_climate
  - platform: device
    device_id: 91bb18af911a9a5f2189a6e544daaf50
    domain: xiaomi_gateway3
    type: action
    state: hold
    id: on_climate
  - platform: time
    at: "05:00:00"
    id: schedule
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - off_climate
              - schedule
        sequence:
          - device_id: 7829ed26160baebf4dd707593af19b91
            domain: climate
            entity_id: 2d29246024b4a5c03e829991d6c4314a
            type: set_hvac_mode
            hvac_mode: "off"
      - conditions:
          - condition: trigger
            id:
              - on_climate
        sequence:
          - device_id: 7829ed26160baebf4dd707593af19b91
            domain: climate
            entity_id: 2d29246024b4a5c03e829991d6c4314a
            type: set_hvac_mode
            hvac_mode: cool
mode: single
```

### What version of Home Assistant Core has the issue?
**core-2024.5.1**

### What was the last working version of Home Assistant Core?
**core-2024.4.1**

### What type of installation are you running?
**Home Assistant OS**

### What version of Home Assistant Supervisor has the issue?
**2024.05.1**

### What version of Home Assistant Operating System has the issue?
**12.2**

### HACS version
**1.34.0**

### JciHitachiHA version
**1.7.0**
